basePath: /
definitions:
  models.Song:
    properties:
      group_name:
        type: string
      id:
        type: integer
      link:
        type: string
      release_date:
        type: string
      song_name:
        type: string
      text:
        type: string
    type: object
host: localhost:2152
info:
  contact: {}
  description: API для управления песнями
  title: Song API
  version: "1.0"
paths:
  /add-song/:
    post:
      description: Добавляет новую песню в базу данных
      parameters:
      - description: Данные песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.Song'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Song'
        "400":
          description: Ошибка в запросе
          schema:
            type: string
      summary: Добавить песню
      tags:
      - songs
  /songs/:
    get:
      description: Возвращает список всех песен
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Song'
            type: array
      summary: Получить список песен
      tags:
      - songs
  /songs/{id}/:
    delete:
      consumes:
      - application/json
      description: Удаляет песню по ID
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Песня успешно удалена
          schema:
            type: string
        "404":
          description: Песня не найдена
          schema:
            type: string
      summary: Удалить песню
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Обновляет информацию о песне по ID
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      - description: Обновленные данные песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Song'
        "400":
          description: Ошибка в запросе
          schema:
            type: string
        "404":
          description: Песня не найдена
          schema:
            type: string
      summary: Обновить песню
      tags:
      - models.Song
swagger: "2.0"
